buffer-size: 1024
window-size: 10
moving-threshold: 10.0
angle-threshold: 15
corner-threshold: 30
allow-diagonal: false
debug: true
gesture:
  - type: Up
    control: control0
  - type: UpRight
    control: control1
  - type: UpLeft
    control: control2
  - type: UpDown
    control: control3
  - type: Down
    control: control4
  - type: DownRight
    control: control5
  - type: DownLeft
    control: control6
  - type: DownDown
    control: control7
  - type: Left
    control: control8
  - type: LeftUp
    control: control9
  - type: LeftDown
    control: controla
  - type: LeftLeft
    control: controlb
  - type: Right
    control: controlc
  - type: RightUp
    control: controld
  - type: RightDown
    control: controle
  - type: RightRight
    control: controlf
